### ISSUE TITLE
Getting Error "operating on too many entity groups in a single transaction." while performing transaction.save(entities)

### ISSUE THREAD

**Issue by adityapol1058** [googleapis/nodejs-datastore#1011]
Hi,
I'm facing an issue while saving the entities to the datastore through transaction. It seems multiple data objects are getting duplicated in "requests_" object of the same transaction, identical multiple objects are getting added
as shown in screenshot attached (highlighted in yellow). This issue is getting reproduced for certain case only, other cases are working correctly even though the entities are almost similar and bigger than this one.
Adding the code snippet and the output I'm getting for reference.
code snippet :
```
transactionEntities.push({
  key: dataObj[0][dataStore.KEY],
  data: dataObj[0]
});
transaction.save(transactionEntities);
await transaction.commit();
```

output : 
{"code":3,"details":"operating on too many entity groups in a single transaction.","level":"error","metadata":{}}

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/37020118/198075029-9b3d7782-8f03-431f-ac54-9ff82d5a5dd2.png">

Pls suggest any solution or acknowledge if this is an open issue.

**Comment by danieljbruce** [comment]
According to [this comment](https://github.com/googleapis/nodejs-datastore/blob/cd59c718ebe6711603b08b3ba2677e5a984bc7e3/src/transaction.ts#L188-L193) about saving with transactions, we shouldn't modify code to divide the save transactions into chunks behind the scenes because even though that should make your error go away, it may not preserve the order desired for some users.

Try doing this after pushing all data to `transactionEntities`:
```
const chunkSize = 10;
for (let i = 0; i < transactionEntities.length; i += chunkSize) {
    const chunk = transactionEntities.slice(i, i + chunkSize);
    transaction.save(chunk);
    await transaction.commit();
}
```
