### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-datastore#103]
Currently blocked by https://github.com/googleapis/gapic-generator/issues/2054

**Comment by jsynowiec** [comment]
Maybe you (maintainers) can contribute to the [@types/google-cloud__datastore](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-cloud__datastore/index.d.ts) until https://github.com/googleapis/gapic-generator/issues/2054 is resolved? Keep it more up to date? It would be easier for you because you're working with the source code.

**Comment by JustinBeckwith** [comment]
This is actually in pretty good shape :) We need to ship a new version, but the types are pretty complete at this stage.
