### ISSUE TITLE
Generated string for keyToLegacyUrlSafe using namespace undefined vs empty string

### ISSUE THREAD

**Issue by bogdan-nourescu** [googleapis/nodejs-datastore#1260]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Yes, i believe its a client library issue (@google-cloud/datastore)

2) Did someone already solve this?
 no other issues found/resolved

3) Do you have a support contract?
no

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Windows
  - Node.js version: 18
  - npm version: 9.6.7
  - `@google-cloud/datastore` version: 8.7.0

#### Steps to reproduce
There is a difference between urlSafe keys generated using the empty string as a namespace and undefined as a namespace.
The empty string one has a few letters extra at the end of the string.

```
const datastore = new Datastore({});
let hash1 = (await datastore.keyToLegacyUrlSafe(datastore.key({namespace:undefined,path: ["Kind", "name"]}), "e~"))
let hash2 = (await datastore.keyToLegacyUrlSafe(datastore.key({namespace:"",path: ["Kind", "name"]}), "e~"))
console.log(hash1, hash2)
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by danieljbruce** [comment]
This behaviour is expected. We want these two hashes to be different because we want `keyFromLegacyUrlsafe` to be the inverse of `keyToLegacyUrlsafe` so every input of `keyToLegacyUrlsafe` should map to a unique value.

That said, we will take an action item to ensure `keyToLegacyUrlsafe` and `keyFromLegacyUrlsafe` are inverses of one another. Please reopen this issue if you have any more questions.
