### ISSUE TITLE
Query datastore entity by url-safe key or decode it to a searchable key

### ISSUE THREAD

**Issue by moshevi** [googleapis/nodejs-datastore#152]
I'm trying to query datastore entity with NodeJS client API (https://www.npmjs.com/package/@google-cloud/datastore) given safe-url string provided by existing Go code. For some reason while other APIs (Go, Python,...) enable to decode/encode from/to safe-Url to key, NodeJS doesn't. Is there other way to do this? Thanks.

#### Environment details

  - OS:
  - Node.js version: 8.9.3
  - npm version: 6.2.0
  - `@google-cloud/datastore` version: 1.4.1

####

**Comment by blainegarrett** [comment]
I have not tried the urlsafe bit yet with node, but my guess is it has to do with the encoding of the int values for the key id. I have existing data that is being wonky trying to serialize due to the default auto id policy: https://cloud.google.com/appengine/docs/standard/python/datastore/entities#Python_Assigning_identifiers
