### ISSUE TITLE
Datastore emulator slows to a crawl after event-stream updates

### ISSUE THREAD

**Issue by chadbr** [googleapis/nodejs-datastore#263]
#### Environment details

  - OS: MacOS (Mojave)
  - Node.js version: 10.x
  - npm version: 6.4.1
  - `@google-cloud/datastore` version: 2.0.0

#### Steps to reproduce

* start the emulator
* write to it

The client writes get slower and slower -- the emulator seems to be running fine:

```
datastore] INFO: Time to persist datastore: 2 ms
[datastore] Nov 29, 2018 3:52:46 PM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Nov 29, 2018 3:52:46 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
[datastore] Nov 29, 2018 3:53:06 PM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub lambda$persist$7
[datastore] INFO: Time to persist datastore: 1 ms
[datastore] Nov 29, 2018 3:55:06 PM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub lambda$persist$7
[datastore] INFO: Time to persist datastore: 2 ms
```

I made a repo here: https://github.com/chadbr/ds-emu-problem

**Comment by chadbr** [comment]
@JustinBeckwith fyi - seems this fix will fix this issue...
https://github.com/grpc/grpc/pull/17383

**Comment by JustinBeckwith** [comment]
@chadbr if memory serves, I *thought* there was a support ticket for this as well.  The problem is right here:
https://github.com/chadbr/ds-emu-problem/blob/master/src/index.ts#L20

Creating a new `Datastore` object is a bit of a heavy operation when connecting to the normal Datastore service.  When you're connecting to the emulator, it's a *super* heavy operation.  If you lift ` const ds = datastore(options);` outside of the loop and only do this once, it should super speed things up. 

Adding in @crwilcox as he did the actual research here 👅

**Comment by chadbr** [comment]
@JustinBeckwith yes - that solved my issue. But the bug "started" because of the grpc bug I noted above (from my support ticket).

The real code has been running fine for about 1.5 years... in any case, I've converted to the connection to a singleton and everything is working fine.

 Chad

**Comment by blainegarrett** [comment]
@chadbr I'm running into the same issue on python 3. To achieve your singleton, are you using some sort of dependency injection like Guice or Dagger for Java or are you just setting a global?
