### ISSUE TITLE
merge operation doesn't work in transaction

### ISSUE THREAD

**Issue by terence410** [googleapis/nodejs-datastore#750]
This is reported since v5. 

If your transaction really has no support on "merge", I suggest you opt out such method in your library.

**Comment by vicb** [comment]
I think that your bug description would benefit from more context and a repro:

> This is reported since v5.

References ?

> If your transaction really has no support on "merge", I suggest you opt out such method in your library.

Do you have a repro.

That being said I find that doc on Transaction is not very helpful.

That is the [Transaction section](https://googleapis.dev/nodejs/datastore/latest/Transaction.html) never mentions that `Transaction` inherits from `DatastoreRequest`. You have to look at the code examples to know that you can call `transaction.get()`. 

It would be great that the `get` method is documented on transactions or at the very least that `Transaction` inherits from `DatastoreRequest`.

**Comment by vicb** [comment]
And have you seen https://github.com/googleapis/nodejs-datastore/pull/694 which is supposed to fix merge in transactions ?

**Comment by meredithslota** [comment]
The linked PR #694 was never merged, due to it being a breaking change. But a comment mentioned we could reconsider when we dropped Node 10: https://github.com/googleapis/nodejs-datastore/pull/694#issuecomment-832942960 It looks like we did that just recently (https://github.com/googleapis/nodejs-datastore/releases/tag/v7.0.0). Related earlier issue with additional repro steps is here: https://github.com/googleapis/nodejs-datastore/issues/547

**Comment by meredithslota** [comment]
@terence410 — I added this same context to your original issue and am going to close this question as a duplicate.
